predator_alert : /vision/predator_alert
<<<<<<< HEAD
input_image_topic: /nao_robot/camera/top/camera/image_raw
=======
input_image_topic: /camera/rgb/image_raw
begin_hunt_topic: /predator/hunt
>>>>>>> upstream/master
